base:
  wandb_enabled: True
main:
  update: False
  update_from: "artifacts/2024/06/27/Run_1/100"
  live_plot: False
  env_id: 'SafetyPointCircle1-v0'
  render_mode: None

  agent:
    name: "DDPG"
    agent_config:
      hidden_size_1: 64
      hidden_size_2: 128
      priority_replay: True

train:
  num_episodes: 10
  batch_size: 64
  max_steps_per_episode: 250
  save_every: 5

test:
  models_dir: "artifacts/2024/06/27/Run_1"
  model_nums: [100, 500, 1000]
  num_runs: 10
  render_mode: None
  max_steps_per_episode: 500



