base:
  wandb_enabled: True
main:
  update: False
  update_from: "artifacts/2024/06/21/Run_1/5444"
  env_id: 'SafetyPointCircle1-v0'
  render_mode: None

  agent:
    name: "CBF_DDPG"
    agent_config:
      hidden_size_1: 64
      hidden_size_2: 128
      priority_replay: True

train:
  num_episodes: 500
  batch_size: 128
  max_steps_per_episode: 250
  save_every: 200
  record_every: 100

test:
  models_dir: "artifacts/2024/07/28/Run_2/"
  model_nums: [800,1000]
  num_runs: 2
  render_mode: 'human'
  max_steps_per_episode: 500



